"""empty message

Revision ID: 6b00d1f72f74
Revises: dee2c88de7fb
Create Date: 2018-03-17 21:46:07.990272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b00d1f72f74'
down_revision = 'dee2c88de7fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'timezone_interval',
        sa.Column('timezone', sa.String(length=120), nullable=False),
        sa.Column('utcoffset', sa.Interval(), nullable=True),
        sa.Column('start', sa.DateTime(timezone=True), nullable=False),
        sa.Column('end', sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint('"start" < "end"'),
        sa.PrimaryKeyConstraint('timezone', 'start', 'end')
    )
    op.create_index(op.f('ix_timezone_interval_end'), 'timezone_interval', ['end'], unique=False)
    op.create_index(op.f('ix_timezone_interval_start'), 'timezone_interval', ['start'], unique=False)
    op.create_index(op.f('ix_timezone_interval_utcoffset'), 'timezone_interval', ['utcoffset'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timezone_interval_utcoffset'), table_name='timezone_interval')
    op.drop_index(op.f('ix_timezone_interval_start'), table_name='timezone_interval')
    op.drop_index(op.f('ix_timezone_interval_end'), table_name='timezone_interval')
    op.drop_table('timezone_interval')
    # ### end Alembic commands ###
