"""empty message

Revision ID: 84b08e8eff56
Revises: 8516e170a4e2
Create Date: 2018-03-28 17:28:12.422798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84b08e8eff56'
down_revision = '8516e170a4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_result', sa.Column('commit_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_result', 'commit_count')
    # ### end Alembic commands ###
