"""empty message

Revision ID: 9c23829e6ef9
Revises: 3e28f27eda85
Create Date: 2018-02-05 11:27:00.366358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c23829e6ef9'
down_revision = '3e28f27eda85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commit', sa.Column('commit_time_offset', sa.Interval(), nullable=True))
    op.add_column('commit', sa.Column('creation_time_offset', sa.Interval(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commit', 'creation_time_offset')
    op.drop_column('commit', 'commit_time_offset')
    # ### end Alembic commands ###
