"""empty message

Revision ID: b0876060d7cf
Revises: fbe7493fe7e4
Create Date: 2018-01-30 19:00:40.678342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0876060d7cf'
down_revision = 'fbe7493fe7e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('commit_repository_commit_sha_fkey', 'commit_repository', type_='foreignkey')
    op.drop_constraint('commit_repository_repository_clone_url_fkey', 'commit_repository', type_='foreignkey')
    op.create_foreign_key(None, 'commit_repository', 'repository', ['repository_clone_url'], ['clone_url'], ondelete='CASCADE', deferrable=True)
    op.create_foreign_key(None, 'commit_repository', 'commit', ['commit_sha'], ['sha'], ondelete='CASCADE', deferrable=True)
    op.create_index(op.f('ix_contributer_organizations_contributer_login'), 'contributer_organizations', ['contributer_login'], unique=False)
    op.create_index(op.f('ix_contributer_organizations_organization_login'), 'contributer_organizations', ['organization_login'], unique=False)
    op.drop_constraint('contributer_organizations_organization_login_fkey', 'contributer_organizations', type_='foreignkey')
    op.drop_constraint('contributer_organizations_contributer_login_fkey', 'contributer_organizations', type_='foreignkey')
    op.create_foreign_key(None, 'contributer_organizations', 'contributer', ['contributer_login'], ['login'], ondelete='CASCADE', deferrable=True)
    op.create_foreign_key(None, 'contributer_organizations', 'organization', ['organization_login'], ['login'], ondelete='CASCADE', deferrable=True)
    op.drop_constraint('contributer_repositories_contributer_login_fkey', 'contributer_repository', type_='foreignkey')
    op.drop_constraint('contributer_repository_repository_clone_url_fkey', 'contributer_repository', type_='foreignkey')
    op.create_foreign_key(None, 'contributer_repository', 'contributer', ['contributer_login'], ['login'], ondelete='CASCADE', deferrable=True)
    op.create_foreign_key(None, 'contributer_repository', 'repository', ['repository_clone_url'], ['clone_url'], ondelete='CASCADE', deferrable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contributer_repository', type_='foreignkey')
    op.drop_constraint(None, 'contributer_repository', type_='foreignkey')
    op.create_foreign_key('contributer_repository_repository_clone_url_fkey', 'contributer_repository', 'repository', ['repository_clone_url'], ['clone_url'])
    op.create_foreign_key('contributer_repositories_contributer_login_fkey', 'contributer_repository', 'contributer', ['contributer_login'], ['login'])
    op.drop_constraint(None, 'contributer_organizations', type_='foreignkey')
    op.drop_constraint(None, 'contributer_organizations', type_='foreignkey')
    op.create_foreign_key('contributer_organizations_contributer_login_fkey', 'contributer_organizations', 'contributer', ['contributer_login'], ['login'], ondelete='CASCADE')
    op.create_foreign_key('contributer_organizations_organization_login_fkey', 'contributer_organizations', 'organization', ['organization_login'], ['login'], ondelete='CASCADE')
    op.drop_index(op.f('ix_contributer_organizations_organization_login'), table_name='contributer_organizations')
    op.drop_index(op.f('ix_contributer_organizations_contributer_login'), table_name='contributer_organizations')
    op.drop_constraint(None, 'commit_repository', type_='foreignkey')
    op.drop_constraint(None, 'commit_repository', type_='foreignkey')
    op.create_foreign_key('commit_repository_repository_clone_url_fkey', 'commit_repository', 'repository', ['repository_clone_url'], ['clone_url'], ondelete='CASCADE')
    op.create_foreign_key('commit_repository_commit_sha_fkey', 'commit_repository', 'commit', ['commit_sha'], ['sha'], ondelete='CASCADE')
    # ### end Alembic commands ###
