"""empty message

Revision ID: bbdaf7e96fbb
Revises: 9c23829e6ef9
Create Date: 2018-02-07 14:02:11.588133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bbdaf7e96fbb'
down_revision = '9c23829e6ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commit', type_='primary')
    op.create_primary_key(None, 'commit', type_='primary')
    op.drop_column('commit', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commit', type_='primary')
    op.add_column('commit', sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_primary_key(None, 'commit', ['id'])
    # ### end Alembic commands ###
