"""empty message

Revision ID: dee2c88de7fb
Revises: 260052013f65
Create Date: 2018-03-13 00:04:54.217130

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dee2c88de7fb'
down_revision = '260052013f65'
branch_labels = None
depends_on = None


def upgrade():
    """Rename contributer to contributor."""
    # Rename and drop contributer_organizations stuff
    op.drop_constraint('contributer_organizations_contributer_login_organization_lo_key', 'contributer_organizations')
    op.drop_constraint('contributer_organizations_contributer_login_fkey', 'contributer_organizations')
    op.drop_constraint('contributer_organizations_organization_login_fkey', 'contributer_organizations')
    op.drop_index('ix_contributer_organizations_contributer_login', table_name='contributer_organizations')
    op.drop_index('ix_contributer_organizations_organization_login', table_name='contributer_organizations')

    op.rename_table('contributer_organizations', 'contributor_organizations')
    op.alter_column('contributor_organizations', 'contributer_login', new_column_name='contributor_login')

    # Rename and drop contributer_repository stuff
    op.drop_constraint('contributer_repository_repository_clone_url_contributer_log_key', table_name='contributer_repository')
    op.drop_constraint('contributer_repository_contributer_login_fkey', 'contributer_repository')
    op.drop_constraint('contributer_repository_repository_clone_url_fkey', 'contributer_repository')
    op.drop_index('ix_contributer_repository_contributer_login', table_name='contributer_repository')
    op.drop_index('ix_contributer_repository_repository_clone_url', table_name='contributer_repository')

    op.rename_table('contributer_repository', 'contributor_repository')
    op.alter_column('contributor_repository', 'contributer_login', new_column_name='contributor_login')

    # Rename and drop stuff from email
    op.alter_column('email', 'contributer_login', new_column_name='contributor_login')
    op.drop_index('ix_email_contributer_login', table_name='email')
    op.drop_constraint('email_contributer_login_fkey', 'email', type_='foreignkey')

    # Rename table
    op.rename_table('contributer', 'contributor')

    # Email stuff
    op.create_index(op.f('ix_email_contributor_login'), 'email', ['contributor_login'], unique=False)
    op.create_foreign_key('email_contributor_login_fkey', 'email', 'contributor', ['contributor_login'], ['login'])

    # Contributor_organization stuff
    op.create_foreign_key(
        'contributor_organizations_contributor_login_fkey',
        'contributor_organizations', 'contributor',
        ['contributor_login'], ['login'],
        onupdate='CASCADE', ondelete='CASCADE', deferrable=True,
    )
    op.create_foreign_key(
        'contributor_organizations_organization_login_fkey',
        'contributor_organizations', 'organization',
        ['organization_login'], ['login'],
        onupdate='CASCADE', ondelete='CASCADE', deferrable=True,
    )
    op.create_unique_constraint('contributer_organizations_contributer_login_organization_lo_key', 'contributor_organizations', ['organization_login', 'contributor_login'])
    op.create_index(op.f('ix_contributor_organizations_contributor_login'), 'contributor_organizations', ['contributor_login'], unique=False)
    op.create_index(op.f('ix_contributor_organizations_organization_login'), 'contributor_organizations', ['organization_login'], unique=False)

    # Contributor_repository stuff
    op.create_foreign_key(
        'contributor_repository_contributor_login_fkey',
        'contributor_repository', 'contributor',
        ['contributor_login'], ['login'],
        onupdate='CASCADE', ondelete='CASCADE', deferrable=True,
    )
    op.create_foreign_key(
        'contributor_repository_repository_clone_url_fkey',
        'contributor_repository', 'repository',
        ['repository_clone_url'], ['clone_url'],
        onupdate='CASCADE', ondelete='CASCADE', deferrable=True,
    )
    op.create_unique_constraint('contributer_repository_repository_clone_url_contributer_log_key', 'contributor_repository', ['repository_clone_url', 'contributor_login'])
    op.create_index(op.f('ix_contributor_repository_contributor_login'), 'contributor_repository', ['contributor_login'], unique=False)
    op.create_index(op.f('ix_contributor_repository_repository_clone_url'), 'contributor_repository', ['repository_clone_url'], unique=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    return
