"""empty message

Revision ID: e5bc054554c6
Revises: 40dac48e0860
Create Date: 2018-02-12 18:42:06.780716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5bc054554c6'
down_revision = '40dac48e0860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commit', sa.Column('unknown', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commit', 'unknown')
    # ### end Alembic commands ###
