"""Add cascades to many to many relationships

Revision ID: fbe7493fe7e4
Revises: 1cb6f96a1d8e
Create Date: 2018-01-29 16:30:33.610945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe7493fe7e4'
down_revision = '1cb6f96a1d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('commit_repository_repository_clone_url_fkey', 'commit_repository', type_='foreignkey')
    op.drop_constraint('commit_repositories_commit_sha_fkey', 'commit_repository', type_='foreignkey')
    op.create_foreign_key(None, 'commit_repository', 'commit', ['commit_sha'], ['sha'], ondelete='CASCADE')
    op.create_foreign_key(None, 'commit_repository', 'repository', ['repository_clone_url'], ['clone_url'], ondelete='CASCADE')
    op.drop_constraint('contributer_organizations_organization_login_fkey', 'contributer_organizations', type_='foreignkey')
    op.drop_constraint('contributer_organizations_contributer_login_fkey', 'contributer_organizations', type_='foreignkey')
    op.create_foreign_key(None, 'contributer_organizations', 'contributer', ['contributer_login'], ['login'], ondelete='CASCADE')
    op.create_foreign_key(None, 'contributer_organizations', 'organization', ['organization_login'], ['login'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contributer_organizations', type_='foreignkey')
    op.drop_constraint(None, 'contributer_organizations', type_='foreignkey')
    op.create_foreign_key('contributer_organizations_contributer_login_fkey', 'contributer_organizations', 'contributer', ['contributer_login'], ['login'])
    op.create_foreign_key('contributer_organizations_organization_login_fkey', 'contributer_organizations', 'organization', ['organization_login'], ['login'])
    op.drop_constraint(None, 'commit_repository', type_='foreignkey')
    op.drop_constraint(None, 'commit_repository', type_='foreignkey')
    op.create_foreign_key('commit_repositories_commit_sha_fkey', 'commit_repository', 'commit', ['commit_sha'], ['sha'])
    op.create_foreign_key('commit_repository_repository_clone_url_fkey', 'commit_repository', 'repository', ['repository_clone_url'], ['clone_url'])
    # ### end Alembic commands ###
